using Lighthouse.Configuration;
using Lighthouse.Data;
using Lighthouse.Extensions;
using Lighthouse.Filters;
using Lighthouse.Middleware;
using Lighthouse.Services;
using Lighthouse.Validators;
using DockerComposeManager.Services.Security;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Serilog;
using System.Text;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

// Optional, gitignored per-developer overrides (e.g. ComposeDiscovery:HostPathMapping).
// Loaded after the default appsettings.{Environment}.json so local values win, and
// before anything reads configuration below. Generated by dev-setup/setup scripts.
builder.Configuration.AddJsonFile(
    $"appsettings.{builder.Environment.EnvironmentName}.local.json",
    optional: true,
    reloadOnChange: true);

// Runtime-controllable minimum log level. Seeded from configuration (env/appsettings),
// later overridden by the persisted value and by the Settings UI. Mutating
// MinimumLevel takes effect immediately across the whole Serilog pipeline.
string? configuredLevel = builder.Configuration["Serilog:MinimumLevel:Default"];
Serilog.Core.LoggingLevelSwitch logLevelSwitch = new(
    Enum.TryParse(configuredLevel, ignoreCase: true, out Serilog.Events.LogEventLevel parsedLevel)
        ? parsedLevel
        : Serilog.Events.LogEventLevel.Information);

// Configure Serilog with explicit assemblies (single-file publish safe)
try
{
    Serilog.Settings.Configuration.ConfigurationReaderOptions readerOptions = new(
        typeof(Serilog.Sinks.SystemConsole.Themes.ConsoleTheme).Assembly,
        typeof(Serilog.Sinks.File.FileSink).Assembly
    );

    Log.Logger = new LoggerConfiguration()
        .ReadFrom.Configuration(builder.Configuration, readerOptions)
        // Override the global Default level with the switch while keeping the
        // namespaced Override entries (Microsoft/System -> Warning) from config.
        .MinimumLevel.ControlledBy(logLevelSwitch)
        .CreateLogger();
}
catch (Exception ex)
{
    // Fallback minimal logger if configuration loading fails
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.ControlledBy(logLevelSwitch)
        .WriteTo.Console()
        .CreateLogger();
    Log.Error(ex, "Failed to initialize Serilog from configuration; fallback console logger in use");
}

builder.Host.UseSerilog();

// Register the level switch and the service that drives it at runtime.
builder.Services.AddSingleton(logLevelSwitch);
builder.Services.AddSingleton<LogLevelService>();

// Ensure log directories exist for any configured file sinks
try
{
    IConfigurationSection writeToSection = builder.Configuration.GetSection("Serilog:WriteTo");
    foreach (IConfigurationSection sink in writeToSection.GetChildren())
    {
        string? path = sink.GetSection("Args").GetValue<string>("path");
        if (!string.IsNullOrWhiteSpace(path))
        {
            string? directory = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
                Log.Information("Created log directory: {LogDirectory}", directory);
            }
        }
    }
}
catch (Exception ex)
{
    Log.Warning(ex, "Failed to ensure log directories for Serilog file sinks");
}

// Add Database Context
string connectionString = builder.Configuration["Database:ConnectionString"] ?? "Data Source=Data/app.db";
builder.Services.AddDbContext<AppDbContext>(options => options
    .UseSqlite(connectionString)
    // Enable WAL + busy_timeout + FK enforcement on every connection.
    .AddInterceptors(new Lighthouse.Data.SqliteConnectionInterceptor()));

// Configure JWT Authentication
string jwtSecret = builder.Configuration["Jwt:Secret"] ?? string.Empty;
if (string.IsNullOrWhiteSpace(jwtSecret))
{
    throw new InvalidOperationException(
        "JWT Secret is not configured. Please set the JWT_SECRET environment variable or Jwt:Secret in appsettings.json. " +
        "The secret must be at least 32 characters long for security.");
}
if (jwtSecret.Length < 32)
{
    throw new InvalidOperationException(
        $"JWT Secret must be at least 32 characters long. Current length: {jwtSecret.Length}. " +
        "Please set a secure JWT_SECRET environment variable.");
}
// Fail fast in production if the shipped placeholder secret was never replaced.
if (builder.Environment.IsProduction() &&
    jwtSecret == "CHANGE-THIS-SECRET-KEY-IN-PRODUCTION-MIN-32-CHARS")
{
    throw new InvalidOperationException(
        "JWT Secret is still the default placeholder. Set a unique JWT_SECRET before running in production.");
}
string jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? "lighthouse";
string jwtAudience = builder.Configuration["Jwt:Audience"] ?? "lighthouse-client";

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = jwtIssuer,
        ValidAudience = jwtAudience,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtSecret)),
        ClockSkew = TimeSpan.FromMinutes(5)
    };

    // Configure JWT authentication for SSE endpoints
    // SSE sends the token in the query string (access_token parameter)
    options.Events = new JwtBearerEvents
    {
        OnMessageReceived = context =>
        {
            Microsoft.Extensions.Primitives.StringValues accessToken = context.Request.Query["access_token"];

            // If the request is for our SSE endpoints
            PathString path = context.HttpContext.Request.Path;
            if (!string.IsNullOrEmpty(accessToken) &&
                (path.StartsWithSegments("/api/events") ||
                 (path.Value != null && path.Value.Contains("/logs/stream"))))
            {
                context.Token = accessToken;
            }

            return Task.CompletedTask;
        },

        // Enforce the per-user security stamp so access tokens can be revoked before
        // their natural expiry (password change, disable, role change). The current
        // stamp/enabled state is cached briefly to avoid a DB hit on every request.
        OnTokenValidated = async context =>
        {
            string? idClaim = context.Principal?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;
            string? stampClaim = context.Principal?.FindFirst("sstamp")?.Value;

            if (!int.TryParse(idClaim, out int uid) || string.IsNullOrEmpty(stampClaim))
            {
                context.Fail("Invalid token subject");
                return;
            }

            Microsoft.Extensions.Caching.Memory.IMemoryCache cache =
                context.HttpContext.RequestServices.GetRequiredService<Microsoft.Extensions.Caching.Memory.IMemoryCache>();

            Lighthouse.Services.Security.UserSecurityInfo? info =
                await cache.GetOrCreateAsync(Lighthouse.Services.Security.SecurityStampCache.Key(uid), async entry =>
                {
                    entry.AbsoluteExpirationRelativeToNow = Lighthouse.Services.Security.SecurityStampCache.Ttl;
                    AppDbContext db = context.HttpContext.RequestServices.GetRequiredService<AppDbContext>();
                    return await db.Users
                        .Where(u => u.Id == uid)
                        .Select(u => new Lighthouse.Services.Security.UserSecurityInfo(u.SecurityStamp, u.IsEnabled))
                        .FirstOrDefaultAsync();
                });

            if (info is null || !info.IsEnabled || info.SecurityStamp != stampClaim)
            {
                context.Fail("Security stamp mismatch");
            }
        }
    };
});

builder.Services.AddAuthorization();

// Configure CORS
string[] corsOrigins = builder.Configuration.GetSection("Cors:Origins").Get<string[]>() ?? ["http://localhost:3030"];
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.WithOrigins(corsOrigins)
              .AllowAnyMethod()
              .AllowAnyHeader()
              .AllowCredentials();
    });
});

// Bind all strongly-typed options classes to their configuration sections
builder.Services.AddAppOptions(builder.Configuration);

// Decrypt embedded Resend API key if present (injected at Docker build time)
string? encryptedResendKey = builder.Configuration["Email:Resend:EncryptedApiKey"];
if (!string.IsNullOrEmpty(encryptedResendKey))
{
    string? decryptedKey = Lighthouse.Security.ApiKeyProtector.Decrypt(encryptedResendKey);
    if (!string.IsNullOrEmpty(decryptedKey))
    {
        builder.Configuration["Email:Resend:ApiKey"] = decryptedKey;
        Log.Information("Resend API key decrypted successfully from embedded configuration");
    }
    else
    {
        Log.Warning("Failed to decrypt embedded Resend API key");
    }
}

// Register email service (based on configuration provider)
// Falls back to Mock if Resend is configured but API key is missing
string emailProvider = builder.Configuration["Email:Provider"] ?? "Mock";
string? resendApiKey = builder.Configuration["Email:Resend:ApiKey"];
if (emailProvider.Equals("Resend", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrEmpty(resendApiKey))
{
    builder.Services.AddScoped<Lighthouse.Services.Email.IEmailService, Lighthouse.Services.Email.ResendEmailService>();
    Log.Information("Email service configured: Resend");
}
else
{
    if (emailProvider.Equals("Resend", StringComparison.OrdinalIgnoreCase))
    {
        // In production a missing key almost certainly means misconfiguration; fail fast
        // rather than silently degrading to a mock that drops password-reset emails.
        if (builder.Environment.IsProduction())
        {
            throw new InvalidOperationException(
                "Email:Provider is 'Resend' but Email:Resend:ApiKey is not configured. " +
                "Set the API key or change the provider before running in production.");
        }
        Log.Warning("Resend provider configured but API key is missing. Falling back to Mock email service");
    }
    builder.Services.AddScoped<Lighthouse.Services.Email.IEmailService, Lighthouse.Services.Email.MockEmailService>();
    Log.Information("Email service configured: Mock (development mode)");
}

// Add Memory Cache (required for ComposeDiscoveryService)
builder.Services.AddMemoryCache();

// Register application services, grouped by subsystem (see ServiceCollectionExtensions).
builder.Services
    .AddApplicationServices()
    .AddComposeServices()
    .AddSelfUpdateServices()
    .AddImageUpdateServices()
    .AddNotificationServices()
    .AddAppBackgroundServices();

// Add FluentValidation
builder.Services.AddFluentValidationAutoValidation();
builder.Services.AddValidatorsFromAssemblyContaining<Program>();

// Add Rate Limiting
builder.Services.ConfigureRateLimiting();

// Add Request Timeouts (required for UseRequestTimeouts middleware)
builder.Services.AddRequestTimeouts();

// Add SSE connection manager, event handler, and crash loop detection (singletons)
builder.Services.AddRealtimeServices();

// Add controllers with validation filter
builder.Services.AddControllers(options =>
{
    options.Filters.Add<ValidateModelStateFilter>();
});

//// Add Swagger/OpenAPI
//builder.Services.AddEndpointsApiExplorer();
//builder.Services.AddSwaggerGen();

WebApplication app = builder.Build();

// Configure validation based on environment
ValidationConfig.IsDevelopment = app.Environment.IsDevelopment();
Log.Information("Validation mode: {Mode}", ValidationConfig.IsDevelopment ? "Development (Relaxed)" : "Production (Strict)");

// Apply migrations and seed data
using (IServiceScope scope = app.Services.CreateScope())
{
    AppDbContext dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    try
    {
        // Ensure database directory exists
        string dbPath = builder.Configuration["Database:ConnectionString"] ?? "Data Source=Data/app.db";
        string? directory = Path.GetDirectoryName(dbPath.Replace("Data Source=", "").Trim());
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
            Log.Information($"Created database directory: {directory}");
        }

        dbContext.Database.Migrate();
        Log.Information("Database migrations applied successfully");
    }
    catch (Exception ex)
    {
        // Fail fast: continuing with an unmigrated/broken schema only produces opaque
        // runtime failures later. Surface the problem at startup instead.
        Log.Fatal(ex, "Error applying database migrations - aborting startup");
        throw;
    }
}

// Apply the persisted log level (if any) now that migrations have run.
await app.Services.GetRequiredService<LogLevelService>().InitializeFromDatabaseAsync();

// Ensure compose files directory exists
IOptions<ComposeDiscoveryOptions> composeOptions = app.Services.GetRequiredService<IOptions<Lighthouse.Configuration.ComposeDiscoveryOptions>>();
string rootPath = composeOptions.Value.RootPath;

if (!Directory.Exists(rootPath))
{
    try
    {
        Directory.CreateDirectory(rootPath);
        Log.Information("Created compose files directory: {Path}", rootPath);
    }
    catch (Exception ex)
    {
        Log.Warning(ex,
            "Could not create compose files directory: {Path}. " +
            "Application will run in degraded mode.", rootPath);
    }
}
else
{
    Log.Information("Compose files directory exists: {Path}", rootPath);
}

// Configure middleware pipeline
if (app.Environment.IsDevelopment())
{
    //app.UseSwagger();
    //app.UseSwaggerUI();
}

// Add Error Handling Middleware first
app.UseMiddleware<ErrorHandlingMiddleware>();

// Configure Serilog request logging to exclude stats endpoints (to prevent log flooding)
app.UseSerilogRequestLogging(options =>
{
    options.GetLevel = (httpContext, elapsed, ex) =>
    {
        // Don't log stats endpoints to prevent flooding
        if (httpContext.Request.Path.StartsWithSegments("/api/containers") &&
            httpContext.Request.Path.Value?.Contains("/stats") == true)
        {
            return Serilog.Events.LogEventLevel.Verbose; // Changed to Verbose (won't show unless explicitly configured)
        }

        // Log errors as Error level
        if (ex != null || httpContext.Response.StatusCode > 499)
        {
            return Serilog.Events.LogEventLevel.Error;
        }

        // Normal requests as Information
        return Serilog.Events.LogEventLevel.Information;
    };
});

app.UseCors();

// Add Security Headers
app.UseSecurityHeaders();

// Add Request Timeouts (enables [RequestTimeout] attribute on endpoints)
app.UseRequestTimeouts();

// Add Rate Limiting
app.UseRateLimiter();

app.UseAuthentication();
app.UseAuthorization();

// Basic health check endpoint (for Docker healthcheck) - just checks if app is running
app.MapGet("/health", () =>
{
    return Results.Ok(new { status = "Healthy", timestamp = DateTime.UtcNow });
})
   .WithName("HealthCheck")
   .WithTags("Health")
   .AllowAnonymous();

// Detailed health check endpoint with DB and Docker verification
app.MapGet("/health/detailed", async (AppDbContext dbContext, DockerService dockerService) =>
{
    Dictionary<string, object> checks = new();
    DateTime startTime = DateTime.UtcNow;
    bool isHealthy = true;

    // Check Database
    try
    {
        await dbContext.Database.CanConnectAsync();
        int userCount = await dbContext.Users.CountAsync();
        checks["database"] = new
        {
            status = "Healthy",
            description = "SQLite database is accessible",
            userCount = userCount
        };
    }
    catch (Exception ex)
    {
        isHealthy = false;
        checks["database"] = new
        {
            status = "Unhealthy",
            description = "Cannot connect to database",
            error = ex.Message
        };
    }

    // Check Docker
    try
    {
        List<Lighthouse.DTOs.ContainerDto> containers = await dockerService.ListContainersAsync(true);
        checks["docker"] = new
        {
            status = "Healthy",
            description = "Docker daemon is reachable",
            containerCount = containers.Count
        };
    }
    catch (Exception ex)
    {
        isHealthy = false;
        checks["docker"] = new
        {
            status = "Unhealthy",
            description = "Cannot connect to Docker daemon",
            error = ex.Message
        };
    }

    TimeSpan totalDuration = DateTime.UtcNow - startTime;

    var response = new
    {
        status = isHealthy ? "Healthy" : "Unhealthy",
        checks = checks,
        totalDuration = totalDuration.ToString(@"hh\:mm\:ss\.fffffff"),
        timestamp = DateTime.UtcNow
    };

    return isHealthy ? Results.Ok(response) : Results.StatusCode(503);
})
   .WithName("HealthCheckDetailed")
   .WithTags("Health")
   // Detailed health exposes user/container counts and raw dependency error messages,
   // so it must not be anonymous. The simple /health endpoint stays public for the
   // Docker container healthcheck.
   .RequireAuthorization(new Microsoft.AspNetCore.Authorization.AuthorizeAttribute { Roles = "admin" });

app.MapControllers();

// Log when application is ready and mark instance as ready
IHostApplicationLifetime lifetime = app.Services.GetRequiredService<IHostApplicationLifetime>();
lifetime.ApplicationStarted.Register(async () =>
{
    IInstanceIdentifierService instanceService = app.Services.GetRequiredService<IInstanceIdentifierService>();

    string[] urls = app.Urls.ToArray();
    if (urls.Length > 0)
    {
        Log.Information("Lighthouse Backend is ready and listening on: {Urls}", string.Join(", ", urls));
    }
    else
    {
        Log.Information("Lighthouse Backend is ready and listening");
    }

    // Verify DB accessibility before marking as ready
    try
    {
        using IServiceScope scope = app.Services.CreateScope();
        AppDbContext dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
        await dbContext.Database.CanConnectAsync();

        // Mark instance as ready
        instanceService.SetReady();
        double uptimeMs = (DateTime.UtcNow - instanceService.StartupTimestamp).TotalMilliseconds;
        Log.Information("Instance {InstanceId} ready after {UptimeMs:F0}ms",
            instanceService.InstanceId, uptimeMs);
    }
    catch (Exception ex)
    {
        Log.Error(ex, "Readiness checks failed - instance {InstanceId} NOT marked as ready",
            instanceService.InstanceId);
    }

    // Log self-filter detection result
    try
    {
        ISelfFilterService selfFilter = app.Services.GetRequiredService<ISelfFilterService>();
        string? selfProject = await selfFilter.GetSelfProjectNameAsync();
        string? selfContainerId = await selfFilter.GetSelfContainerIdAsync();

        if (selfProject != null)
        {
            Log.Information(
                "Self-filter active: project '{SelfProject}', container '{SelfContainerId}' will be hidden from all lists",
                selfProject, selfContainerId);
        }
        else if (selfContainerId != null)
        {
            Log.Information(
                "Self-filter active: standalone container '{SelfContainerId}' will be hidden from all lists",
                selfContainerId);
        }
        else
        {
            Log.Information("Self-filter inactive: not running in Docker");
        }
    }
    catch (Exception ex)
    {
        Log.Warning(ex, "Failed to log self-filter detection result");
    }
});

lifetime.ApplicationStopping.Register(() =>
{
    Log.Information("Lighthouse Backend is stopping...");
});

Log.Information("Lighthouse Backend starting...");
app.Run();
Log.Information("Lighthouse Backend stopped");
